apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - deployment.yaml
  - service.yaml
images:
  - name: kamaldocker29/kubernetes
    newTag: 85e29f52d1d4fee607e160f8a36594581f86d182
