apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - deployment.yaml
  - service.yaml
images:
  - name: kamaldocker29/kubernetes
    newTag: 53e07c3e26ba94412d7c65afc9066cb6218ecb5c
