apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - deployment.yaml
  - service.yaml
images:
  - name: kamaldocker29/kubernetes
    newTag: 1567126176b831f8e750b16191fce884a676b9e2
